### ISSUE TITLE
request for more customizing ;)

### ISSUE THREAD

**Issue by xCite1986** [marcelwinh/MMM-PimaticFloorplan#1]
hey marcel.

thank you for your plugin.. Pimatic that way looks really nice in MagicMirror :)

i have some requests for you, it would be cool if you could extend this functions:

- is it possible to give the values unit-labels like 12**°C**  or 55**%** and set a wording or an custom icon before the value?
so it would be possible to display "**Vorzimmer:** 23.5**°C**" or show an icon of an thermometer before the value.

- the icon for the light was only shown if the light was powered on, is it possible to show a different png-icon if the light was off?

- it would be geneally nice to set a custom png-icon for a device like a stove, tv or computer to show the power-state of the device

maybe you have time for some code :)

thanks in advance
Alex

**Comment by marcelwinh** [comment]
> is it possible to give the values unit-labels like 12°C or 55**%** and set a wording or an custom icon before the value?
so it would be possible to display "Vorzimmer: 23.5°C" or show an icon of an thermometer before the value.

postfix: '\u00B0C' &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;// for unit label/text after value e.g. °C
prefix: 'Vorzimmer: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;// for text before value
image: 'customImage.png'&nbsp;&nbsp;// for custom image before text
````javascript
Temperature_Wohnzimmer_soll:    { left: 80,  top: 85, color: "grey", decimals: 1, pimaticId: "thermostat-couch.temperatureSetpoint", postfix: '\u00B0C', prefix: 'WZ Soll', image: 'customImage.png'},
````
>the icon for the light was only shown if the light was powered on, is it possible to show a different png-icon if the light was off?

new default light images:
````javascript
light: { // this part shows default settings for lights; may optionally be overwritten
	imageOn: "lightOn.png", // located in subfolder 'images'
	imageOff: "lightOff.png", // located in subfolder 'images'
	width: 25, // image width
	height: 25, // image height
},
````
>it would be geneally nice to set a custom png-icon for a device like a stove, tv or computer to show the power-state of the device

new custom images in lights:
````javascript
lights: {
	tv_status:   { left: 15, top: 140, pimaticId: "tv-status.presence", imageOn: 'tvOn.png', imageOff:'tvOff.png'}, // value of pimaticId has to be of type boolean
},
````
